import {copy} from './content.js';

export const chapters={en:['Introduction','Harmonije / GlasAI','Kraguj / Sheetpost','Services & process','About & toolkit','Contact'],sr:['Uvod','Harmonije / GlasAI','Kraguj / Sheetpost','Usluge i proces','O meni i veštine','Kontakt']};
export const bookCopy={
 en:{edition:'AN INDEPENDENT PERSPECTIVE',role:'Web Developer & AI Product Builder',promise:'Turning ideas into polished digital experiences.',instruction:'Open the book. Explore my work.',open:'Open the book',close:'Close book',contents:'Contents',read:'Reading view',back:'Back to the book',prev:'Previous spread',next:'Next spread',reset:'Reset view',hint:'Drag to rotate · Scroll to zoom · ← → to turn',mobileHint:'Swipe to turn · Drag with two fingers to rotate · Pinch to zoom',touch:'Get in touch ↗',location:'BELGRADE, SERBIA',selected:'SELECTED WORK / 2026',loading:'Preparing the desk…',fallback:'A quieter edition. The complete portfolio, without 3D.',page:'Spread',leaf:'Page',leafPrev:'Previous page',leafNext:'Next page',case:'Read case study',live:'View project ↗',ready:'Available for new projects',note:'Six chapters. Four projects. One considered approach.',intro:'Digital experiences, built with intention.',introText:'I’m Stefan, an independent web developer and AI product builder based in Belgrade. I create custom websites and interactive product experiences, from the first brief to frontend polish and production QA.',caption:'Design. Engineer. Refine.',services:'Good ideas deserve thoughtful execution.',process:'From an imperfect brief to something real.',about:'Ambition, with attention to detail.',toolkit:'The tools behind the work.',contact:'Have something worth building?',exceptional:'Let’s make it exceptional.',contactText:'Tell me what you’re working on. We’ll define the scope, the path forward, and a price that fits the project.',closing:'Every detail is a decision.',overview:'Full portfolio',turn:'Turn page',web:'WEB DEVELOPMENT · DIGITAL EXPERIENCES'},
 sr:{edition:'NEZAVISNA PERSPEKTIVA',role:'Web developer i graditelj AI proizvoda',promise:'Ideje pretvaram u doterana digitalna iskustva.',instruction:'Otvori knjigu. Istraži moje radove.',open:'Otvori knjigu',close:'Zatvori knjigu',contents:'Sadržaj',read:'Prikaz za čitanje',back:'Nazad na knjigu',prev:'Prethodni dvostrani prikaz',next:'Sledeći dvostrani prikaz',reset:'Resetuj pogled',hint:'Prevuci za rotaciju · Skroluj za zum · ← → za stranice',mobileHint:'Prevuci za stranice · Dva prsta za rotaciju · Spoji prste za zum',touch:'Javi se ↗',location:'BEOGRAD, SRBIJA',selected:'IZABRANI RADOVI / 2026',loading:'Pripremam radni sto…',fallback:'Mirnije izdanje. Ceo portfolio, bez 3D prikaza.',page:'Dvostrani prikaz',leaf:'Stranica',leafPrev:'Prethodna stranica',leafNext:'Sledeća stranica',case:'Detalji projekta',live:'Otvori projekat ↗',ready:'Dostupan za nove projekte',note:'Šest poglavlja. Četiri projekta. Promišljen pristup.',intro:'Digitalna iskustva, građena sa namerom.',introText:'Ja sam Stefan, nezavisni web developer i graditelj AI proizvoda iz Beograda. Izrađujem sajtove i interaktivna iskustva proizvoda, od prvog zahteva do dorade interfejsa i produkcionog QA-a.',caption:'Dizajn. Razvoj. Dorada.',services:'Dobre ideje zaslužuju pažljivu izradu.',process:'Od nepotpunog zahteva do stvarnog rešenja.',about:'Ambicija i pažnja prema detaljima.',toolkit:'Alati iza mojih radova.',contact:'Imaš nešto što vredi napraviti?',exceptional:'Napravimo nešto izuzetno.',contactText:'Opiši šta želiš da napraviš. Definisaćemo obim, sledeće korake i cenu koja odgovara projektu.',closing:'Svaki detalj je odluka.',overview:'Ceo portfolio',turn:'Okreni stranicu',web:'WEB RAZVOJ · DIGITALNA ISKUSTVA'}
};
export const projectImages={honey:new URL('../assets/projects/harmonije-desktop-2026-10-04.jpg',import.meta.url).href,glas:new URL('../assets/images/glasai.jpg',import.meta.url).href,gym:new URL('../assets/images/gimnastika-kraguj.jpg',import.meta.url).href,sheet:new URL('../assets/images/sheetpost.jpg',import.meta.url).href};
export const projects=[{id:'honey',title:'Harmonije<br>Panonije',url:'https://harmonije-panonije.vercel.app/',number:'01',tech:'Next.js / React / TypeScript / Playwright'}, {id:'glas',title:'GlasAI',url:'https://www.glasai.online/',number:'02',tech:'Serbian voice demo / Product interface'}, {id:'gym',title:'Gimnastika<br>Kraguj',url:'https://gimnastika-kraguj.vercel.app/',number:'03',tech:'Responsive UI / Content / Schedules'}, {id:'sheet',title:'Sheetpost',url:'https://sheetpost-seven.vercel.app/',number:'04',tech:'CSV mapping / Validation / Multilingual UI'}];
const page=(title,num,content,extra='')=>`<article class="book-page ${extra}" aria-label="${title}"><div class="page-masthead"><span>SB / SELECTED DIGITAL WORK</span><span>2026</span></div>${content}<div class="page-folio"><span>STEFAN BRKLJAČIĆ</span><span>${num}</span></div></article>`;
const projectPage=(project,lang)=>{
 const d=copy[lang],b=bookCopy[lang],id=project.id;
 return page(project.title.replace('<br>',' '),String(Number(project.number)+3).padStart(2,'0'),`<div class="page-kicker">${project.number} / ${d[id+'Status']}</div><h2>${project.title}</h2><div class="project-art art-${id}"><img src="${projectImages[id]}" alt="${d['alt'+({honey:'Honey',glas:'Glas',gym:'Gym',sheet:'Sheet'}[id])]}" width="1200" height="800"><span class="art-label">${id==='honey'?'PANONIJA / DIGITAL CATALOGUE':id==='glas'?'VOICE / INTERACTION':id==='gym'?'MOVEMENT / COMMUNITY':'DATA / WORKFLOW'}</span></div><p class="page-description">${d[id+'Solution']}</p><div class="page-contribution"><span>${d.caseContribution}</span><p>${d[id+'Role']}</p></div><p class="page-constraint">${d[id+'Constraints']}</p><p class="compact-qualifier">${({honey:lang==='sr'?'Katalog · bez onlajn naplate.':'Catalogue · no online checkout.',glas:lang==='sr'?'Koncept · bez produkcionih integracija.':'Concept · no production integrations.',gym:lang==='sr'?'Javni pregled · zvanična objava nije potvrđena.':'Public preview · official launch unconfirmed.',sheet:lang==='sr'?'Prototip · slanje je simulirano.':'Prototype · submission is simulated.'})[id]}</p><div class="page-actions"><a href="${project.url}" target="_blank" rel="noopener noreferrer">${b.live}</a><button type="button" data-case="${id}">${b.case} +</button></div>`, 'project-page');
};
function spreadMarkup(index,lang='en') {
 const b=bookCopy[lang],d=copy[lang];
 const folio=(title,num,content,cls)=>page(title,num,content,cls);
 const toc=[['01',lang==='sr'?'Uvod':'Introduction',0],['02','Harmonije Panonije',1],['03','GlasAI',1,1],['04','Gimnastika Kraguj',2],['05','Sheetpost',2,1],['06',lang==='sr'?'Usluge i proces':'Services & process',3],['07',lang==='sr'?'O meni i veštine':'About & capabilities',4],['08',lang==='sr'?'Kontakt':'Contact',5]];
 switch(index) {
 case 0:return [folio(b.contents,'02',`<div class="page-kicker">VOL. 01 / ${b.location}</div><h2>${b.contents}<span class="serif-dot">.</span></h2><p class="page-deck">${b.note}</p><nav class="page-contents" aria-label="${b.contents}">${toc.map(([n,t,s,side=0])=>`<button type="button" data-spread="${s}" data-leaf="${side}"><small>${n}</small><span>${t}</span><i>↗</i></button>`).join('')}</nav><div class="contents-foot">${b.caption}<span>SB</span></div>`),folio(b.intro,'03',`<div class="page-kicker">01 / ${chapters[lang][0]}</div><h2 class="intro-title">${b.intro}</h2><div class="architecture-art" aria-hidden="true"><div class="architecture-layer layer-one"><i></i><i></i><i></i></div><div class="architecture-layer layer-two"><span>STRUCTURE</span></div><div class="architecture-layer layer-three"><span>EXPERIENCE</span><b>SB</b></div><small>IDEA → INTERFACE → EXPERIENCE</small></div><p class="page-description">${b.introText}</p><div class="page-signature">Stefan Brkljačić <span>Belgrade · 2026</span></div>`,'intro-page')];
 case 1:return projects.slice(0,2).map(p=>projectPage(p,lang));
 case 2:return projects.slice(2).map(p=>projectPage(p,lang));
 case 3:return [folio(chapters[lang][3],'08',`<div class="page-kicker">06 / ${d.navServices}</div><h2>${b.services}</h2><div class="page-services">${[1,2,3].map(n=>`<section><small>0${n}</small><h3>${d['service'+n+'Title']}</h3><p>${d['service'+n+'Text']}</p></section>`).join('')}</div><p class="page-constraint">${d.price1} · ${lang==='sr'?'Cena i rok prema dogovorenom obimu.':'Pricing and timing depend on agreed scope.'}</p><a class="page-contact" data-inquiry href="mailto:stefanbrkk@gmail.com">${b.touch}</a>`),folio(b.process,'09',`<div class="page-kicker">06 / ${d.navMethod}</div><h2>${b.process}</h2><div class="page-process">${[1,2,3,4,5,6].map(n=>`<div><small>0${n}</small><span>${d['method'+n+'Title']}</span><i>↓</i></div>`).join('')}</div><p class="page-description">${d.manifestoP2}</p><p class="page-constraint">${d.aboutAI}</p>`)];
 case 4:return [folio(d.navAbout,'10',`<div class="page-kicker">07 / ${d.navAbout}</div><h2>${b.about}</h2><div class="about-monogram" aria-hidden="true">SB<span>44.7866° N<br>20.4489° E</span></div><p class="page-description">${d.aboutLead}</p><p class="page-description">${d.aboutAI}</p><div class="education-note"><span>${d.factEducation}</span><h3>${d.educationSchool.replaceAll('<br>',' ')}</h3><p>${d.educationTrack} · 2024–2028</p></div>`),folio(b.toolkit,'11',`<div class="page-kicker">07 / ${lang==='sr'?'VEŠTINE':'CAPABILITIES'}</div><h2>${b.toolkit}</h2><div class="toolkit-list">${['React / Next.js','TypeScript / JavaScript',lang==='sr'?'Arhitektura interfejsa':'Frontend architecture',lang==='sr'?'Prilagodljiv UI':'Responsive UI',lang==='sr'?'Animacije i interakcije':'Motion & interaction',lang==='sr'?'AI-potpomognut razvoj':'AI-assisted development',lang==='sr'?'Pristupačnost i SEO':'Accessibility & SEO','Playwright / QA','Vercel / Deployment'].map((s,i)=>`<div><small>${String(i+1).padStart(2,'0')}</small><span>${s}</span></div>`).join('')}</div><p class="page-constraint">${d.aboutPrinciple2}</p>`)];
 default:return [folio(b.contact,'12',`<div class="page-kicker">08 / ${d.navContact}</div><h2>${b.contact}</h2><h3 class="contact-italic">${b.exceptional}</h3><p class="page-description">${b.contactText}</p><a class="page-contact" data-inquiry href="mailto:stefanbrkk@gmail.com">${b.touch}</a><a class="book-email" href="mailto:stefanbrkk@gmail.com">stefanbrkk@gmail.com</a><div class="book-socials"><a href="https://github.com/stefanbrkkk" target="_blank" rel="noopener noreferrer">GitHub ↗</a><a href="https://www.linkedin.com/in/stefan-brklja%C4%8Di%C4%87-13258942a/" target="_blank" rel="noopener noreferrer">LinkedIn ↗</a></div>`,'contact-page'),folio(b.closing,'13',`<div class="closing-monogram">SB<span>STEFAN BRKLJAČIĆ</span></div><p class="closing-caption">${b.caption}</p><button type="button" class="page-contact close-book" data-close-book>${b.close} ↗</button>`,'closing-page')];
 }
}

export function spreadHTML(index,lang='en') {
 const replacements=[['SELECTED DIGITAL WORK','IZABRANI DIGITALNI RADOVI'],['PANONIJA / DIGITAL CATALOGUE','PANONIJA / DIGITALNI KATALOG'],['VOICE / INTERACTION','GLAS / INTERAKCIJA'],['MOVEMENT / COMMUNITY','POKRET / ZAJEDNICA'],['DATA / WORKFLOW','PODACI / RADNI TOK'],['IDEA → INTERFACE → EXPERIENCE','IDEJA → INTERFEJS → ISKUSTVO'],['STRUCTURE','STRUKTURA'],['EXPERIENCE','ISKUSTVO'],['Belgrade · 2026','Beograd · 2026'],['Vercel / Deployment','Vercel / Objavljivanje']];
 return spreadMarkup(index,lang).map(html=>lang==='sr'?replacements.reduce((text,[en,sr])=>text.replaceAll(en,sr),html):html);
}
