/** @type {Record<'en'|'sr', Record<string, string>>} */
export const copy = {
  "en": {
    "imageUnavailable": "Preview unavailable. Open project.",
    "processNotes": "Implementation & QA notes",
    "caseStudy": "Case study",
    "caseProblem": "Problem",
    "caseContribution": "Contribution",
    "caseConstraint": "Constraint",
    "caseSolution": "Solution",
    "caseDeliverables": "Deliverables",
    "emailDirect": "Email directly",
    "dialogLanguage": "Switch to Serbian",
    "dialogGoal": "Project goal (optional)",
    "dialogCurrentUrl": "Current website URL (optional)",
    "dialogTiming": "Desired timing (optional)",
    "dialogContextHelp": "Your optional context is added to this message when you copy it or open an email draft.",
    "dialogEmailDesc": "Open a draft in your email app",
    "dialogCopyFallback": "Select and copy this complete message manually",

    "skip": "Skip to content",
    "navWork": "Work",
    "navServices": "Services",
    "navMethod": "Method",
    "navAbout": "About",
    "navContact": "Contact",
    "heroEyebrow": "Independent web developer · AI product builder",
    "heroIntro": "I turn incomplete briefs into polished, testable web experiences — from first structure to production QA and deployment.",
    "heroRole": "React · Next.js · TypeScript",
    "heroMeta": "Client websites · product demos · QA",
    "scroll": "Scroll to deconstruct",
    "manifestoEyebrow": "What I optimize for",
    "manifestoTitle": "Digital work that feels <em>intentional</em>, not assembled.",
    "manifestoP1": "The visible layer matters: hierarchy, rhythm, motion and the exact moment an interface responds. But the work has to survive the invisible layer too — responsive states, keyboard use, production builds and real client revisions.",
    "manifestoP2": "My workflow is deliberately end-to-end: define the structure, build the interface, break it, test it, deploy it, then refine what real feedback exposes.",
    "workEyebrow": "Selected work",
    "honeyText": "A catalogue and inquiry website — search, category discovery, multi-product quantities, custom motion, mobile layouts and a production-oriented QA chain.",
    "liveSite": "Live site",
    "glasText": "A Serbian-language AI receptionist concept translated into a clear product site and interactive voice demo for appointment-based businesses.",
    "liveDemo": "Live demo",
    "aiCardTitle": "Incoming call",
    "aiCardBody": "Natural-language demo layer designed around the way appointment businesses actually receive requests.",
    "gymText": "A responsive club website preview that makes programmes, group schedules, trainer information, calendar links and trial-class inquiries easier to find.",
    "livePreview": "Live preview",
    "sheetText": "A multilingual spreadsheet/CSV-to-invoice workflow prototype for Poland’s KSeF context — import, column mapping, validation, structured preview and simulated KSeF submission. No live KSeF integration.",
    "mappingTitle": "Map → validate → preview",
    "anatomyEyebrow": "How I work",
    "anatomyTitle": "From brief.<br><em>To launch.</em>",
    "anatomyStaticText": "Define the brief, build the interface, review the result, then deploy. These layers support each step.",
    "anatomyText": "Brief → design/build → review → launch. Scroll to see how the layers connect.",
    "shipBadge": "Verified. Shipped.",
    "phaseExplore": "Decompose the system",
    "phaseInspect": "Inspect the layers",
    "phaseRecompose": "Recompose the build",
    "phaseShip": "Ready to ship",
    "methodEyebrow": "How I work",
    "methodTitle": "Implementation<br><em>and verification.</em>",
    "methodState1": "Define",
    "method1Title": "Brief",
    "method1Text": "Turn an incomplete request into one concrete user problem, a content map and a clear path to action.",
    "method1Meta": "goals → content → user path",
    "methodState2": "Structure",
    "method2Title": "Architecture",
    "method2Text": "Define components, states, content boundaries and the implementation shape before visual complexity begins.",
    "method2Meta": "components → states → data",
    "methodState3": "Compose",
    "method3Title": "Interface",
    "method3Text": "Build hierarchy, responsive states and tactile UI so the experience remains legible before motion is added.",
    "method3Meta": "hierarchy → responsive → interaction",
    "methodState4": "Choreograph",
    "method4Title": "Motion",
    "method4Text": "Use scroll, depth and hover only where they explain structure or create a deliberate moment — with reduced-motion and touch-safe fallbacks.",
    "method4Meta": "timing → continuity → feedback",
    "methodState5": "Prove",
    "method5Title": "Verification",
    "method5Text": "Break the interface before users can: responsive review, keyboard/focus behavior, accessibility, lint/type checks, production build and behavioral testing where the project supports it.",
    "method5Meta": "responsive → a11y → QA → build",
    "methodState6": "Release",
    "method6Title": "Ship",
    "method6Text": "Deploy the finished system, observe what real feedback exposes, and refine the parts that matter instead of treating launch as the end.",
    "method6Meta": "production → feedback → iteration",
    "servicesEyebrow": "What I can build",
    "servicesTitle": "Focused scope.<br>Serious execution.",
    "service1Title": "Small-business websites",
    "service2Title": "Product prototypes",
    "service3Title": "Frontend polish & QA",
    "aboutEyebrow": "About",
    "aboutText": "The part I care about most is the handoff between taste and engineering: a site should feel considered, but it should also survive real content, smaller screens, keyboard navigation, production builds and revision cycles.",
    "factBase": "Base",
    "factRole": "Focus",
    "factRoleVal": "Web development · product demos · frontend QA",
    "factStack": "Stack",
    "factQuality": "Quality",
    "factEducation": "Education",
    "factEducationVal": "Ninth Belgrade Gymnasium “Mihailo Petrović Alas” · Natural Sciences & Mathematics · 2024–2028 · straight-A",
    "contactKicker": "Have something worth building?",
    "contactTitle": "Build it.<br><em>Properly.</em>",
    "emailMe": "Tell me about your project ↗",
    "footerBuilt": "Websites for small businesses & product teams — Belgrade / remote.",
    "signalBrief": "Brief",
    "signalInterface": "Interface",
    "signalMotion": "Motion",
    "signalVerify": "Verify",
    "signalShip": "Ship",
    "signalCenter": "Tell me about your project ↗",
    "signalSmall": "Start the brief",
    "signalCaption": "From first brief to shipped build",
    "dialogKicker": "Project starter",
    "dialogTitle": "What do you want to work on?",
    "dialogText": "Choose a project type or start with a question. Edit your draft, then choose how to contact me.",
    "dialogWebsite": "Website",
    "dialogPrototype": "Product prototype",
    "dialogPolish": "Frontend polish & QA",
    "dialogQA": "Q&A / quick question",
    "dialogWebsiteDesc": "New or redesigned business website",
    "dialogPrototypeDesc": "Interactive product or workflow demo",
    "dialogPolishDesc": "Responsive UI, accessibility, motion and QA",
    "dialogQADesc": "Ask about a site, idea or possible engagement",
    "dialogPrepared": "Editable message",
    "dialogChange": "Reset draft",
    "dialogGmail": "Open a pre-filled Gmail draft",
    "dialogLinkedIn": "Open Stefan’s profile",
    "dialogCopy": "Copy message",
    "dialogCopyDesc": "Use it anywhere you prefer",
    "dialogNote": "Your draft stays on this page until you leave. Nothing is sent automatically; you send it in your chosen app.",
    "contactIntro": "Choose what you need, get a ready-to-send message, and contact me in the channel you already use.",
    "startKicker": "Low-friction start",
    "startStatus": "Three clear steps",
    "startStep1Title": "Tell me the problem",
    "startStep2Title": "Get a scoped plan",
    "startStep3Title": "Build, review, ship",
    "faqKicker": "Before we talk",
    "faqStatus": "Tap a question",
    "educationKicker": "Education",
    "educationTrack": "Natural Sciences & Mathematics track",
    "educationStart": "Started",
    "educationGrad": "Expected graduation",
    "educationGrade": "Straight-A student",
    "educationStatus": "Current student",
    "aboutPrinciple1": "Taste + engineering",
    "aboutPrinciple2": "Real builds, not mock claims",
    "aboutPrinciple3": "QA before handoff",
    "respProofNote": "Harmonije Panonije browser captures from 4 October 2026: 1440×900, 768×1024 and 390×844. These illustrate viewport layouts; device frames do not establish physical-device testing.",
    "available": "Available for new projects",
    "heroPromise": "Client websites and interactive product prototypes — designed, built and reviewed in Belgrade.",
    "ctaStart": "Start a project",
    "ctaWork": "See the work",
    "ctaStrip": "Have a project like these? Describe it in two sentences — you’ll get a scoped plan and a clear quote.",
    "copyEmail": "Copy email",
    "viewLive": "View live site ↗",
    "pmRole": "Role",
    "pmStatus": "Status",
    "pmOutcome": "Result",
    "honeyOut": "Catalogue + pre-filled inquiry flow, mobile-first",
    "glasOut": "Visitors try the Serbian voice agent in-browser",
    "gymOut": "Programmes, schedules and trial signup easy to find",
    "sheetOut": "Invoice mapping, validation and simulated KSeF submission",
    "inc1a": "Custom design & copy structure",
    "inc1b": "Responsive, accessible, SEO-ready",
    "inc1c": "Deployment and agreed review rounds",
    "inc2a": "Flows & interactive demo",
    "inc2b": "Testable deployed build",
    "inc2c": "Iteration from real feedback",
    "inc3a": "Responsive & a11y audit + fixes",
    "inc3b": "Behavioral tests where applicable",
    "inc3c": "Production build verification",
    "price1": "Contact for pricing",
    "term1": "Scope-dependent · typically 1–2 weeks",
    "price2": "Contact for pricing",
    "term2": "Scope-dependent · typically 2–3 weeks",
    "price3": "Contact for pricing",
    "term3": "Scope-dependent · typically 3–5 days",
    "svcCta": "Discuss this project",
    "startTitle": "How we start",
    "start1": "A 30-minute call or email — you describe the problem.",
    "start2": "You get a scoped plan and a clear quote based on the project.",
    "start3": "I build, you review, we launch — then I stay for fixes.",
    "faqTitle": "Quick answers",
    "faq1q": "What do you need from me?",
    "faq1a": "A short description of your business and goal, plus content (text/photos) if you have it. I can help with everything else.",
    "faq2q": "How long does a website take?",
    "faq2a": "Timing depends on scope, confirmed content and review availability. A small website may take 1–2 weeks; a prototype may take 2–3. We agree the schedule in the quote.",
    "faq3q": "What if I need changes later?",
    "faq3a": "Review rounds and post-launch support are agreed in the project scope. I remain available to discuss fixes and additions.",
    "faq4q": "Do you work outside Belgrade?",
    "faq4a": "Yes — remote, in Serbian or English, across time zones.",
    "respEyebrow": "Responsive by default",
    "respTitle": "Every screen, <em>every time.</em>",
    "respText": "From 360px phones to wide desktops — the same interface, adapted and reviewed across representative viewport widths before launch.",
    "vR": "Responsive",
    "vRv": "360–1440px",
    "vK": "Keyboard / focus",
    "vKv": "reviewed",
    "vT": "Type / lint",
    "vTv": "checked",
    "vP": "Production build",
    "vPv": "verified",
    "vB": "Behavioral QA",
    "vBv": "Playwright where applicable",
    "vM": "Reduced motion",
    "vMv": "fallbacks",
    "si1": "01 — WORK",
    "si2": "02 — SERVICES",
    "si3": "03 — ANATOMY",
    "si4": "04 — PROCESS",
    "si5": "05 — ABOUT",
    "pn1": "01 / CLIENT WEBSITE",
    "pn2": "02 / PRODUCT CONCEPT",
    "pn3": "03 / PUBLIC PREVIEW",
    "pn4": "04 / WORKFLOW PROTOTYPE",
    "footLoc": "Belgrade / Serbia",
    "aboutAI": "AI accelerates parts of my workflow. Every shipped result is reviewed, tested and owned by me.",
    "workTitle": "Real projects.<br>Real problems solved.",
    "aboutTitle": "Shipped work first.<br><em>Everything else after.</em>",
    "aboutLead": "I build client websites and interactive product experiences in Belgrade while studying Natural Sciences & Mathematics at Ninth Belgrade Gymnasium.",
    "methodText": "Technical notes on the decisions, checks and handoff behind a website or prototype.",
    "service1Text": "A professional website for your business — structure, responsive design, build and launch, centered on the action you want customers to take: call, order, book.",
    "service2Text": "An interactive web demo of your product idea — something you can put in front of users or investors before you build the real thing.",
    "service3Text": "Your existing site, hardened: responsive fixes, accessibility, speed, SEO and a verified production build before any campaign goes live.",
    "ariaPrimary": "Primary navigation",
    "ariaHome": "Stefan Brkljačić home",
    "ariaSections": "Sections",
    "ariaMenu": "Menu",
    "ariaMobile": "Mobile navigation",
    "ariaStart": "Project start process",
    "ariaProof": "Website captures at desktop, tablet and mobile viewport sizes",
    "ariaTypes": "Project types",
    "ariaSignal": "Project process signal",
    "ariaClose": "Close",
    "ariaType": "Project type",
    "switchLanguage": "Switch language to Serbian",
    "ariaHoney": "Open Harmonije Panonije website",
    "ariaGlas": "Open GlasAI concept demo",
    "ariaGym": "Open Gimnastika Kraguj public preview",
    "ariaSheet": "Open Sheetpost prototype",
    "altHoney": "Screenshot of the Harmonije Panonije website",
    "altGlas": "Screenshot of the GlasAI concept site",
    "altGym": "Screenshot of the Gimnastika Kraguj website preview",
    "altSheet": "Screenshot of the Sheetpost prototype",
    "altLaptop": "Harmonije Panonije website captured at a 1440 by 900 desktop viewport",
    "altTablet": "Harmonije Panonije website captured at a 768 by 1024 tablet viewport",
    "altPhone": "Harmonije Panonije website captured at a 390 by 844 phone viewport",
    "deviceLaptop": "Desktop · 1440×900",
    "deviceTablet": "Tablet · 768×1024",
    "devicePhone": "Phone · 390×844",
    "educationSchool": "Ninth Belgrade Gymnasium<br><em>“Mihailo Petrović Alas”</em>",
    "factBaseVal": "Belgrade, Serbia / Remote",
    "factQualityVal": "Playwright · accessibility · SEO · cross-browser QA · production build verification",
    "buildUrl": "https://your-next-project.rs / production",
    "layerBrief": "Brief",
    "layerBriefMeta": "goal / content / user path",
    "layerArchitecture": "Architecture",
    "layerArchitectureMeta": "routes / states / data",
    "layerInterface": "Interface",
    "layerInterfaceMeta": "hierarchy / responsive UI",
    "layerMotion": "Motion",
    "layerMotionMeta": "timing / feedback / rhythm",
    "layerVerification": "Verification",
    "layerVerificationMeta": "QA / accessibility / build",
    "methodNumber1": "01 / BRIEF",
    "methodNumber2": "02 / ARCHITECTURE",
    "methodNumber3": "03 / INTERFACE",
    "methodNumber4": "04 / MOTION",
    "methodNumber5": "05 / VERIFICATION",
    "methodNumber6": "06 / SHIP",
    "tagVoice": "Voice demo",
    "tagProduct": "Product design",
    "tagResponsive": "Responsive UI",
    "tagScheduling": "Scheduling",
    "tagContent": "Content systems",
    "tagWorkflow": "Workflow UX",
    "tagCSV": "CSV mapping",
    "tagValidation": "Validation",
    "tagMultilingual": "Multilingual",
    "heroCoordinates": "44.7866° N / 20.4489° E<br>Belgrade / Serbia / 2026",
    "webTag": "interactive interface / 01",
    "webTagStructure": "architecture exposed",
    "webTagRecompose": "system recomposed",
    "webLogo": "SB / DIGITAL"
  },
  "sr": {
    "imageUnavailable": "Prikaz nije dostupan. Otvori projekat.",
    "processNotes": "Beleške o izradi i proveri kvaliteta",
    "caseStudy": "Studija projekta",
    "caseProblem": "Problem",
    "caseContribution": "Doprinos",
    "caseConstraint": "Ograničenje",
    "caseSolution": "Rešenje",
    "caseDeliverables": "Isporučeno",
    "emailDirect": "Pošalji imejl direktno",
    "dialogLanguage": "Prebaci na engleski",
    "dialogGoal": "Cilj projekta (opciono)",
    "dialogCurrentUrl": "Adresa postojećeg sajta (opciono)",
    "dialogTiming": "Željeni rok (opciono)",
    "dialogContextHelp": "Opcioni podaci se dodaju poruci kada je kopiraš ili otvoriš nacrt imejla.",
    "dialogEmailDesc": "Otvori nacrt u svojoj imejl aplikaciji",
    "dialogCopyFallback": "Označi i ručno kopiraj celu poruku",

    "skip": "Preskoči na sadržaj",
    "navWork": "Radovi",
    "navServices": "Usluge",
    "navMethod": "Proces",
    "navAbout": "O meni",
    "navContact": "Kontakt",
    "heroEyebrow": "Nezavisni web programer · graditelj AI proizvoda",
    "heroIntro": "Pretvaram nepotpune briefove u doterana, testirana web iskustva — od prve strukture do produkcionog QA-a i deploya.",
    "heroRole": "React · Next.js · TypeScript",
    "heroMeta": "Klijentski sajtovi · demonstracije proizvoda · QA",
    "scroll": "Skroluj za rastavljanje",
    "manifestoEyebrow": "Šta optimizujem",
    "manifestoTitle": "Digitalni rad koji deluje <em>namerno</em>, ne sklopljeno.",
    "manifestoP1": "Vidljivi sloj je bitan: hijerarhija, ritam, pokret i tačan trenutak kada interfejs reaguje. Rad mora da izdrži i prilagođavanje ekranima, korišćenje tastature, produkcione verzije i stvarne klijentske izmene.",
    "workEyebrow": "Izabrani radovi",
    "liveSite": "Otvori sajt",
    "glasText": "Sajt i interaktivna glasovna demonstracija koncepta AI recepcionera na srpskom, namenjenog delatnostima koje rade sa zakazivanjem termina.",
    "liveDemo": "Otvori demo",
    "aiCardTitle": "Dolazni poziv",
    "aiCardBody": "Demo sloj na prirodnom jeziku, dizajniran oko načina na koji biznisi sa terminima stvarno primaju zahteve.",
    "gymText": "Javni pregled sajta gimnastičkog kluba, prilagođen različitim ekranima, sa programima, rasporedima, trenerima, vezama ka kalendaru i upitima za probni trening.",
    "livePreview": "Otvori javni pregled",
    "sheetText": "Višejezični prototip toka od tabele ili CSV datoteke do fakture za poljski KSeF kontekst — uvoz, mapiranje kolona, provera podataka, strukturirani pregled i simulirano slanje u KSeF. Nema stvarne KSeF integracije.",
    "mappingTitle": "Mapiraj → proveri → pregledaj",
    "anatomyEyebrow": "Kako radim",
    "anatomyTitle": "Od zahteva.<br><em>Do objave.</em>",
    "anatomyStaticText": "Definiši zahtev, izgradi interfejs, proveri rezultat, pa objavi. Ovi slojevi podržavaju svaki korak.",
    "anatomyText": "Zahtev → dizajn i izrada → provera → objava. Skroluj da vidiš kako se slojevi povezuju.",
    "shipBadge": "Provereno. Isporučeno.",
    "phaseExplore": "Rastavljanje sistema",
    "phaseInspect": "Pregled slojeva",
    "phaseRecompose": "Sklapanje celine",
    "phaseShip": "Spremno za isporuku",
    "methodEyebrow": "Kako radim",
    "methodTitle": "Izrada<br><em>i provera.</em>",
    "methodText": "Tehničke beleške o odlukama, proverama i predaji sajta ili prototipa.",
    "methodState1": "Definiši",
    "method1Title": "Zahtev",
    "method1Text": "Pretvori nepotpun zahtev u jedan konkretan korisnički problem, mapu sadržaja i jasan put do akcije.",
    "method1Meta": "ciljevi → sadržaj → put korisnika",
    "methodState2": "Struktura",
    "method2Title": "Arhitektura",
    "method2Text": "Definiši komponente, stanja, granice sadržaja i oblik implementacije pre nego što počne vizuelna kompleksnost.",
    "method2Meta": "komponente → stanja → podaci",
    "methodState3": "Sastavi",
    "method3Title": "Interfejs",
    "method3Text": "Izgradi hijerarhiju, stanja za različite ekrane i jasan interfejs tako da iskustvo bude čitljivo i pre nego što se doda pokret.",
    "method3Meta": "hijerarhija → različiti ekrani → interakcija",
    "methodState4": "Koreografija",
    "method4Title": "Pokret",
    "method4Text": "Koristi skrol, dubinu i prelazak pokazivača samo kada objašnjavaju strukturu ili stvaraju nameran trenutak — uz podršku za smanjeno kretanje i dodir.",
    "method4Meta": "trajanje → kontinuitet → odgovor",
    "methodState5": "Dokaži",
    "method5Title": "Provera",
    "method5Text": "Proveri interfejs pre korisnika: prikaz na različitim ekranima, tastaturu i fokus, pristupačnost, provere koda i tipova, produkcionu verziju i testove ponašanja tamo gde projekat to podržava.",
    "method5Meta": "ekrani → pristupačnost → QA → izrada",
    "methodState6": "Isporuči",
    "method6Title": "Isporuka",
    "method6Text": "Objavi završen sistem, posmatraj šta povratne informacije otkriju i doradi ono što je bitno. Objava je početak daljeg unapređivanja.",
    "method6Meta": "objava → povratne informacije → dorada",
    "servicesEyebrow": "Šta mogu da napravim",
    "servicesTitle": "Jasan obim.<br>Ozbiljna izvedba.",
    "service1Title": "Sajtovi za male biznise",
    "service2Title": "Prototipi proizvoda",
    "service3Title": "Dorade interfejsa i QA",
    "aboutEyebrow": "O meni",
    "aboutText": "Najviše me zanima spoj ukusa i inženjerstva: sajt treba da deluje promišljeno, ali mora da izdrži pravi sadržaj, manje ekrane, navigaciju tastaturom, produkcione verzije i cikluse izmena.",
    "factBase": "Baza",
    "factRole": "Fokus",
    "factRoleVal": "Web razvoj · demonstracije proizvoda · QA interfejsa",
    "factStack": "Tehnologije",
    "factQuality": "Kvalitet",
    "factEducation": "Obrazovanje",
    "factEducationVal": "Deveta beogradska gimnazija „Mihailo Petrović Alas” · prirodno-matematički smer · 2024–2028 · odličan uspeh",
    "contactKicker": "Imaš nešto što vredi napraviti?",
    "contactTitle": "Napravimo ga.<br><em>Kako treba.</em>",
    "emailMe": "Ispričaj mi o projektu ↗",
    "footerBuilt": "Sajtovi za male biznise i timove koji razvijaju proizvode — Beograd / rad na daljinu.",
    "signalBrief": "Zahtev",
    "signalInterface": "Interfejs",
    "signalMotion": "Pokret",
    "signalVerify": "Provera",
    "signalShip": "Isporuka",
    "signalCenter": "Ispričaj mi o projektu ↗",
    "signalSmall": "Opiši zahtev",
    "signalCaption": "Od prvog zahteva do objavljene verzije",
    "dialogKicker": "Početak projekta",
    "dialogTitle": "Na čemu želiš da radimo?",
    "dialogText": "Izaberi vrstu projekta ili počni pitanjem. Uredi nacrt, pa izaberi kako da me kontaktiraš.",
    "dialogWebsite": "Web sajt",
    "dialogPrototype": "Prototip proizvoda",
    "dialogPolish": "Dorade interfejsa i QA",
    "dialogQA": "Kratko pitanje",
    "dialogWebsiteDesc": "Novi ili redizajnirani poslovni sajt",
    "dialogPrototypeDesc": "Interaktivna demonstracija proizvoda ili radnog toka",
    "dialogPolishDesc": "Različiti ekrani, pristupačnost, pokret i QA",
    "dialogQADesc": "Pitaj me o sajtu, ideji ili mogućoj saradnji",
    "dialogPrepared": "Poruka za uređivanje",
    "dialogChange": "Resetuj nacrt",
    "dialogGmail": "Otvori unapred popunjenu Gmail poruku",
    "dialogLinkedIn": "Otvori Stefanov profil",
    "dialogCopy": "Kopiraj poruku",
    "dialogCopyDesc": "Iskoristi je gde god želiš",
    "dialogNote": "Nacrt ostaje na ovoj stranici dok je ne napustiš. Ništa se ne šalje automatski; poruku šalješ u izabranoj aplikaciji.",
    "contactIntro": "Izaberi šta ti treba, dobićeš spremnu poruku, a zatim me kontaktiraš kanalom koji već koristiš.",
    "startKicker": "Lak početak",
    "startStatus": "Tri jasna koraka",
    "startStep1Title": "Opiši problem",
    "startStep2Title": "Dobij plan i ponudu",
    "startStep3Title": "Gradimo, pregledamo, objavljujemo",
    "faqKicker": "Pre razgovora",
    "faqStatus": "Otvori pitanje",
    "educationKicker": "Obrazovanje",
    "educationTrack": "Prirodno-matematički smer",
    "educationStart": "Početak",
    "educationGrad": "Planirani završetak",
    "educationGrade": "Odličan uspeh",
    "educationStatus": "Trenutno učenik",
    "aboutPrinciple1": "Ukus + inženjering",
    "aboutPrinciple2": "Stvarni projekti, bez izmišljenih tvrdnji",
    "aboutPrinciple3": "QA pre predaje",
    "respProofNote": "Prikazi sajta Harmonije Panonije u pregledaču od 4. oktobra 2026: 1440×900, 768×1024 i 390×844. Ilustruju raspored na različitim širinama; okviri uređaja nisu dokaz testiranja na fizičkim uređajima.",
    "available": "Dostupan za nove projekte",
    "heroPromise": "Klijentski sajtovi i interaktivni prototipi proizvoda — dizajnirani, izrađeni i pregledani u Beogradu.",
    "ctaStart": "Pokreni projekat",
    "ctaWork": "Pogledaj radove",
    "ctaStrip": "Imate projekat poput ovih? Opišite ga u dve rečenice — dobijate jasan plan i ponudu.",
    "copyEmail": "Kopiraj email",
    "viewLive": "Otvori sajt ↗",
    "pmRole": "Uloga",
    "pmStatus": "Status",
    "pmOutcome": "Rezultat",
    "honeyOut": "Katalog i unapred popunjeni upiti, prilagođeni telefonu",
    "glasOut": "Posetioci isprobavaju glasovnog agenta na srpskom",
    "gymOut": "Programi, rasporedi i prijava lako vidljivi",
    "sheetOut": "Mapiranje faktura, provera podataka i simulirano slanje u KSeF",
    "inc1a": "Sopstveni dizajn i struktura sadržaja",
    "inc1b": "Prilagođen ekranima, pristupačan, spreman za SEO",
    "inc1c": "Objava i dogovorene runde pregleda",
    "inc2a": "Tokovi i interaktivni demo",
    "inc2b": "Objavljena verzija za testiranje",
    "inc2c": "Iteracije iz stvarnih povratnih informacija",
    "inc3a": "Pregled i dorade ekrana i pristupačnosti",
    "inc3b": "Testovi ponašanja gde su primenljivi",
    "inc3c": "Provera produkcione verzije",
    "price1": "Javite se za cenu",
    "term1": "Prema obimu · obično 1–2 nedelje",
    "price2": "Javite se za cenu",
    "term2": "Prema obimu · obično 2–3 nedelje",
    "price3": "Javite se za cenu",
    "term3": "Prema obimu · obično 3–5 dana",
    "svcCta": "Razgovarajmo o projektu",
    "startTitle": "Kako počinjemo",
    "start1": "Trideset minuta poziva ili email — opišete problem.",
    "start2": "Dobijate jasan plan i ponudu prema obimu projekta.",
    "start3": "Gradim, pregledate, objavljujemo — ostajem tu za popravke.",
    "faqTitle": "Brzi odgovori",
    "faq1q": "Šta vam je potrebno od mene?",
    "faq1a": "Kratak opis delatnosti i cilja, i sadržaj (tekst i fotografije) ako ga imate. Za sve ostalo mogu da pomognem.",
    "faq2q": "Koliko traje izrada sajta?",
    "faq2a": "Rok zavisi od obima, potvrđenog sadržaja i dostupnosti za pregled. Manji sajt može trajati 1–2 nedelje, prototip 2–3. Raspored dogovaramo u ponudi.",
    "faq3q": "Šta ako zatrebaju izmene kasnije?",
    "faq3a": "Runde pregleda i podršku posle objave dogovaramo u obimu projekta. Dostupan sam za razgovor o popravkama i dopunama.",
    "faq4q": "Da li radite sa klijentima van Beograda?",
    "faq4a": "Da — na daljinu, na srpskom ili engleskom, u različitim vremenskim zonama.",
    "respEyebrow": "Prilagođen različitim ekranima",
    "respTitle": "Svaki ekran, <em>svaki put.</em>",
    "respText": "Od telefona širine 360px do velikih ekrana — isti interfejs, prilagođen i pregledan kroz reprezentativne širine pre objave.",
    "vR": "Različiti ekrani",
    "vRv": "360–1440px",
    "vK": "Tastatura / fokus",
    "vKv": "pregledano",
    "vT": "Tipovi / lint",
    "vTv": "provereno",
    "vP": "Produkcijska verzija",
    "vPv": "proveren",
    "vB": "Testovi ponašanja",
    "vBv": "Playwright gde je primenljivo",
    "vM": "Smanjeno kretanje",
    "vMv": "prilagođen prikaz",
    "si1": "01 — RADOVI",
    "si2": "02 — USLUGE",
    "si3": "03 — ANATOMIJA",
    "si4": "04 — PROCES",
    "si5": "05 — O MENI",
    "pn1": "01 / KLIJENTSKI SAJT",
    "pn2": "02 / KONCEPT PROIZVODA",
    "pn3": "03 / JAVNI PREGLED",
    "pn4": "04 / PROTOTIP RADNOG TOKA",
    "footLoc": "Beograd / Srbija",
    "aboutAI": "AI ubrzava delove mog rada. Svaki isporučen rezultat pregledam, testiram i za njega odgovaram ja.",
    "workTitle": "Stvarni projekti.<br>Stvarni rešeni problemi.",
    "aboutTitle": "Prvo isporučeno.<br><em>Ostalo posle.</em>",
    "aboutLead": "Gradim klijentske sajtove i interaktivna iskustva proizvoda u Beogradu dok pohađam prirodno-matematički smer Devete beogradske gimnazije.",
    "service1Text": "Profesionalan sajt za vaš biznis — struktura, dizajn, izrada i objava, usmereni na radnju koju korisnik treba da uradi: poziv, upit za porudžbinu ili zakazivanje.",
    "service2Text": "Interaktivni web demo vaše ideje — nešto što možete pokazati korisnicima ili investitorima pre nego što se gradi pravo rešenje.",
    "service3Text": "Dorade postojećeg sajta: prikaz na različitim ekranima, pristupačnost, brzina, SEO i provera produkcione verzije pre objave.",
    "manifestoP2": "Moj postupak je namerno od početka do kraja: definišem strukturu, gradim interfejs, namerno ga lomim, testiram, objavljujem, pa doteram ono što stvarne povratne informacije otkriju.",
    "honeyText": "Katalog i sajt za upite — pretraga, kategorije, količine za više proizvoda, posebni mobilni rasporedi i lanac provera pre objave.",
    "ariaPrimary": "Glavna navigacija",
    "ariaHome": "Stefan Brkljačić — početna",
    "ariaSections": "Odeljci",
    "ariaMenu": "Meni",
    "ariaMobile": "Mobilna navigacija",
    "ariaStart": "Proces početka projekta",
    "ariaProof": "Prikazi sajtova na veličinama za računar, tablet i telefon",
    "ariaTypes": "Tipovi projekta",
    "ariaSignal": "Prikaz procesa projekta",
    "ariaClose": "Zatvori",
    "ariaType": "Tip projekta",
    "switchLanguage": "Prebaci jezik na engleski",
    "ariaHoney": "Otvori sajt Harmonije Panonije",
    "ariaGlas": "Otvori demonstraciju koncepta GlasAI",
    "ariaGym": "Otvori javni pregled Gimnastike Kraguj",
    "ariaSheet": "Otvori prototip Sheetpost",
    "altHoney": "Snimak sajta Harmonije Panonije",
    "altGlas": "Snimak sajta koncepta GlasAI",
    "altGym": "Snimak javnog pregleda sajta Gimnastika Kraguj",
    "altSheet": "Snimak prototipa Sheetpost",
    "altLaptop": "Sajt Harmonije Panonije prikazan u pregledaču veličine 1440 puta 900",
    "altTablet": "Sajt Harmonije Panonije prikazan u pregledaču veličine 768 puta 1024",
    "altPhone": "Sajt Harmonije Panonije prikazan u pregledaču veličine 390 puta 844",
    "deviceLaptop": "Računar · 1440×900",
    "deviceTablet": "Tablet · 768×1024",
    "devicePhone": "Telefon · 390×844",
    "educationSchool": "Deveta beogradska gimnazija<br><em>„Mihailo Petrović Alas”</em>",
    "factBaseVal": "Beograd, Srbija / rad na daljinu",
    "factQualityVal": "Playwright · pristupačnost · SEO · QA u različitim pregledačima · provera produkcione verzije",
    "buildUrl": "https://your-next-project.rs / objavljeno",
    "layerBrief": "Zahtev",
    "layerBriefMeta": "cilj / sadržaj / put korisnika",
    "layerArchitecture": "Arhitektura",
    "layerArchitectureMeta": "putanje / stanja / podaci",
    "layerInterface": "Interfejs",
    "layerInterfaceMeta": "hijerarhija / različiti ekrani",
    "layerMotion": "Pokret",
    "layerMotionMeta": "trajanje / odgovor / ritam",
    "layerVerification": "Provera",
    "layerVerificationMeta": "QA / pristupačnost / izrada",
    "methodNumber1": "01 / ZAHTEV",
    "methodNumber2": "02 / ARHITEKTURA",
    "methodNumber3": "03 / INTERFEJS",
    "methodNumber4": "04 / POKRET",
    "methodNumber5": "05 / PROVERA",
    "methodNumber6": "06 / ISPORUKA",
    "tagVoice": "Glasovna demonstracija",
    "tagProduct": "Dizajn proizvoda",
    "tagResponsive": "Interfejs za različite ekrane",
    "tagScheduling": "Rasporedi",
    "tagContent": "Sistemi sadržaja",
    "tagWorkflow": "Iskustvo radnog toka",
    "tagCSV": "Mapiranje CSV podataka",
    "tagValidation": "Provera podataka",
    "tagMultilingual": "Višejezično",
    "heroCoordinates": "44.7866° N / 20.4489° E<br>Beograd / Srbija / 2026",
    "webTag": "interaktivni prikaz / 01",
    "webTagStructure": "prikaz arhitekture",
    "webTagRecompose": "ponovo sklopljen sistem",
    "webLogo": "SB / DIGITALNO"
  }
};

/** @typedef {{id:string,title:string,status:string,role:string,problem:string,constraints:string,solution:string,deliverables:string,links:Array<{label:string,href:string}>}} ProjectRecord */
/** @type {Record<'en'|'sr', ProjectRecord[]>} */
const projectRecords = {
  "en": [
    {
      "id": "honey",
      "status": "Client catalogue and inquiry website",
      "role": "Design, development and QA",
      "problem": "Help visitors find products and ask about several items in one inquiry.",
      "constraints": "The flow is inquiry-based: quantities prepare a request, without payment checkout.",
      "solution": "Search and category discovery lead to product quantities and a pre-filled inquiry; custom motion has dedicated mobile layouts.",
      "deliverables": "Responsive Next.js catalogue, multi-product inquiry flow and a pre-deploy chain with lint, type checks, production build and Playwright behavioral tests.",
      "links": [
        {
          "label": "Live site",
        },
        {
          "label": "GitHub source",
        }
      ]
    },
    {
      "id": "glas",
      "status": "Interactive concept demo",
      "role": "Product site and interactive voice demo development",
      "problem": "Make a Serbian-language AI receptionist concept understandable and testable for appointment-based businesses.",
      "constraints": "Concept/demo only. No production call routing, booking integrations or customer adoption is claimed.",
      "solution": "A product site explains call-handling use cases and offers an interactive Serbian-language voice demo.",
      "deliverables": "Product site and in-browser voice demo for exploring the concept.",
      "links": [
        {
          "label": "Live demo",
        }
      ]
    },
    {
      "id": "gym",
      "status": "Public preview",
      "role": "Responsive website preview development",
      "problem": "Bring club programmes, group schedules, trainer information and trial-class inquiries into one clear experience.",
      "constraints": "Client content and scheduling rules evolved during development. This is a public preview, with final official launch unconfirmed.",
      "solution": "Organize programmes, schedules and trainer information with calendar links and a trial-class inquiry path.",
      "deliverables": "Responsive public website preview with programme discovery, scheduling information and trial-class inquiries.",
      "links": [
        {
          "label": "Live preview",
        }
      ]
    },
    {
      "id": "sheet",
      "status": "Multilingual workflow prototype",
      "role": "Multilingual workflow prototype development",
      "problem": "Make spreadsheet/CSV-to-invoice steps inspectable for Poland’s KSeF context.",
      "constraints": "Submission is simulated. The prototype has no live KSeF integration and makes no production-compliance claim.",
      "solution": "Import a spreadsheet or CSV, map columns, validate data and inspect a structured invoice preview before simulated submission.",
      "deliverables": "Multilingual, multi-step import, mapping, validation and preview workflow with simulated KSeF submission.",
      "links": [
        {
          "label": "Live demo",
        }
      ]
    }
  ],
  "sr": [
    {
      "id": "honey",
      "status": "Klijentski katalog i sajt za upite",
      "role": "Dizajn, razvoj i QA",
      "problem": "Pomoći posetiocima da pronađu proizvode i pošalju jedan upit za više artikala.",
      "constraints": "Tok se zasniva na upitima: količine pripremaju zahtev, bez naplate na sajtu.",
      "solution": "Pretraga i kategorije vode do izbora količina i unapred popunjenog upita; animacije imaju posebne mobilne rasporede.",
      "deliverables": "Prilagodljiv Next.js katalog, upit za više proizvoda i lanac provera pre objave: lint, provera tipova, produkciona verzija i Playwright testovi ponašanja.",
      "links": [
        {
          "label": "Otvori sajt",
        },
        {
          "label": "GitHub izvorni kod",
        }
      ]
    },
    {
      "id": "glas",
      "status": "Interaktivna demonstracija koncepta",
      "role": "Razvoj sajta proizvoda i interaktivne glasovne demonstracije",
      "problem": "Predstaviti koncept AI recepcionera na srpskom delatnostima koje rade sa terminima, tako da može da se isproba.",
      "constraints": "Samo koncept i demonstracija. Nema produkcionog usmeravanja poziva, integracija za zakazivanje ni tvrdnji o korisnicima.",
      "solution": "Sajt objašnjava primere obrade poziva i nudi interaktivnu glasovnu demonstraciju na srpskom.",
      "deliverables": "Sajt proizvoda i glasovna demonstracija u pregledaču za istraživanje koncepta.",
      "links": [
        {
          "label": "Otvori demo",
        }
      ]
    },
    {
      "id": "gym",
      "status": "Javni pregled",
      "role": "Razvoj javnog pregleda sajta prilagođenog različitim ekranima",
      "problem": "Povezati programe kluba, rasporede grupa, informacije o trenerima i upite za probni trening u jasno iskustvo.",
      "constraints": "Klijentski sadržaj i pravila rasporeda menjali su se tokom razvoja. Ovo je javni pregled; konačna zvanična objava nije potvrđena.",
      "solution": "Organizovati programe, rasporede i informacije o trenerima uz veze ka kalendaru i put do upita za probni trening.",
      "deliverables": "Javni pregled sajta prilagođenog različitim ekranima, sa programima, rasporedima i upitima za probni trening.",
      "links": [
        {
          "label": "Otvori javni pregled",
        }
      ]
    },
    {
      "id": "sheet",
      "status": "Višejezični prototip radnog toka",
      "role": "Razvoj višejezičnog prototipa radnog toka",
      "problem": "Učiniti korake od tabele ili CSV datoteke do fakture preglednim za poljski KSeF kontekst.",
      "constraints": "Slanje je simulirano. Prototip nema stvarnu KSeF integraciju i ne tvrdi da je usklađen za produkcionu upotrebu.",
      "solution": "Uvesti tabelu ili CSV, mapirati kolone, proveriti podatke i pregledati strukturiranu fakturu pre simuliranog slanja.",
      "deliverables": "Višejezični tok uvoza, mapiranja, provere i pregleda u više koraka, sa simuliranim slanjem u KSeF.",
      "links": [
        {
          "label": "Otvori demo",
        }
      ]
    }
  ]
};
for (const language of ['en', 'sr']) {
  for (const project of projectRecords[language]) {
    for (const field of ['status', 'role', 'problem', 'constraints', 'solution', 'deliverables']) {
      copy[language][project.id + field[0].toUpperCase() + field.slice(1)] = project[field];
    }
    project.links.forEach((link, index) => { copy[language][project.id + 'Link' + index] = link.label; });
  }
}
